import React from "react";
import PropTypes from "prop-types";
import { Table, Box, Text } from "rimble-ui";
/**
 * PropsTable
 * Table for React props generated by react-docgen
 *
 * @see https://github.com/episodeyang/react-component-props-table/
 */
const PropsTable = props => {
  let { propMetaData = [], ..._props } = props;
  return (
    <Box>
      {propMetaData.length > 0 ? (
        <Table {..._props}>
          <thead>
            <tr>
              <th>Prop Name</th>
              <th>Type</th>
              <th>Is Required</th>
              <th>Default Value</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            {Object.keys(propMetaData).map(key => {
              const prop = propMetaData[key];
              return (
                <tr key={key}>
                  <td>{prop.name}</td>
                  <td>{prop.parentType ? prop.parentType.name : ""}</td>
                  {prop.required ? <td>required</td> : <td>optional</td>}
                  {prop.defaultValue ? (
                    <td>{prop.defaultValue.value}</td>
                  ) : (
                    <td>none</td>
                  )}
                  <td>
                    {prop.docblock ? prop.docblock : ""}
                    {prop.parentType && prop.parentType.name === "enum" && (
                      <Box>
                        <Text.span>Allowed values: </Text.span>
                        {Object.keys(prop.type.value).map(key => {
                          const value = prop.type.value[key];
                          return (
                            <Text.span key={key}>{value.value}, </Text.span>
                          );
                        })}
                      </Box>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </Table>
      ) : (
        <Text>No props defined for this component.</Text>
      )}
    </Box>
  );
};

PropsTable.propTypes = {
  /** Props from gatsby-transformer-react-docgen  */
  propMetaData: PropTypes.array
};
PropsTable.defaultProps = {
  propMetaData: []
};

export default PropsTable;
